name: Release

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
            deno-version: v1.x
      - run: deno task json
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "output/lexicon.json"
          tag: lastest
          token: ${{ secrets.GITHUB_TOKEN }}